name: Docker-BuildAndPush
on: [push]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  Docker-BuildAndPush:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2.3.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: docker build -t techverito-docker .

      - name: Tag Docker Image
        run: docker tag techverito-docker:latest 136052446758.dkr.ecr.us-east-2.amazonaws.com/techverito:latest

      - name: Push Image to ECR
        run: docker push 136052446758.dkr.ecr.us-east-2.amazonaws.com/techverito:latest