name: Docker-BuildAndPush
on: [push]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  Docker-BuildAndPush:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2.3.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: docker build -t techverito-docker .

      - name: Tag Docker Image
        run: docker tag techverito-docker:latest 136052446758.dkr.ecr.us-east-2.amazonaws.com/techverito:latest

      - name: Push Image to ECR
        id: push-image
        run: docker push 136052446758.dkr.ecr.us-east-2.amazonaws.com/techverito:latest

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can be deployed to ECS.
          docker build -t techverito-docker .
          docker tag techverito-docker:latest 136052446758.dkr.ecr.us-east-2.amazonaws.com/techverito:latest
          docker push 136052446758.dkr.ecr.us-east-2.amazonaws.com/techverito:latest
          echo "::set-output name=image::136052446758.dkr.ecr.us-east-2.amazonaws.com/techverito:latest"    

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition techverito-ecs \
          --query taskDefinition > task-definition.json        

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: techverito-container
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: techverito-ecs-service
          cluster: techverito-ecs-cluster
          wait-for-service-stability: true
