name: Docker-BuildAndPush
on: [push]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  Docker-BuildAndPush:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2.3.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAR7LK3SYTNVKPYJWL
          aws-secret-access-key: 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
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

#      - name: Generate Image Name
#        run: |
#          IMAGE_TAG=`echo $GITHUB_REF | sed "s/refs\/heads\///g" | awk '{print(tolower($0))}' | sed 's|/|-|g'`;
#          echo "ECR_TAG="$IMAGE_TAG"" >> ${GITHUB_ENV};
#          echo "FULL_IMAGE_NAME="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_RESOURCE_NAME_PREFIX }}:$IMAGE_TAG"" >> ${GITHUB_ENV}

      - name: Build Docker Image
        run: docker build -t techverito .

      - name: Push Image to ECR
        run: docker push public.ecr.aws/v1l4z3d8/techverito:latest